<?php
// app/models/User.php

namespace App\Models;

use PDO;
use PDOException;

class User extends \App\Core\BaseModel {

    /**
     * Finds a user by their email address.
     * Could be adapted to find by username if you have a separate username field.
     *
     * @param string $email
     * @return array|false The user data as an associative array, or false if not found.
     */
    public function findByEmail(string $email): array|false {
        try {
            $stmt = $this->db->prepare("SELECT UserID, Email, PasswordHash, RoleID, FullName, IsActive FROM Users WHERE Email = :email LIMIT 1");
            $stmt->bindParam(':email', $email);
            $stmt->execute();
            return $stmt->fetch(PDO::FETCH_ASSOC);
        } catch (PDOException $e) {
            // Log error
            error_log("Error finding user by email: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Finds a user by their UserID.
     * @param string $userId
     * @return array|false
     */
    public function findById(string $userId): array|false {
        try {
            // Assuming RoleName is needed from Roles table
            $sql = "SELECT u.UserID, u.Email, u.FullName, u.RoleID, u.IsActive, r.RoleName
                    FROM Users u
                    JOIN Roles r ON u.RoleID = r.RoleID
                    WHERE u.UserID = :userId LIMIT 1";
            $stmt = $this->db->prepare($sql);
            $stmt->bindParam(':userId', $userId, PDO::PARAM_STR); // Assuming UserID is UUID (string)
            $stmt->execute();
            return $stmt->fetch(PDO::FETCH_ASSOC);
        } catch (PDOException $e) {
            error_log("Error finding user by ID: " . $e->getMessage());
            return false;
        }
    }


    /**
     * Verifies a user's password against the stored hash.
     *
     * @param string $password The plain-text password to verify.
     * @param string $hashedPassword The stored hashed password.
     * @return bool True if the password matches, false otherwise.
     */
    public function verifyPassword(string $password, string $hashedPassword): bool {
        return password_verify($password, $hashedPassword);
    }

    /**
     * (Conceptual) Creates a new user.
     * In a real application, this would include more validation and error handling.
     *
     * @param string $fullName
     * @param string $email
     * @param string $password
     * @param int $roleId
     * @return string|false The new UserID on success, false on failure.
     */
    public function createUser(string $fullName, string $email, string $password, int $roleId): string|false {
        try {
            $passwordHash = password_hash($password, PASSWORD_ARGON2ID); // Or PASSWORD_DEFAULT
            // Assuming UserID is a UUID generated by the database or PHP
            // For this example, let's assume it's handled by the DB or you generate it before calling
            // $userId = ... // generate UUID here if not auto-generated by DB

            // For simplicity, if your UserID is auto-increment integer:
            // $stmt = $this->db->prepare("INSERT INTO Users (FullName, Email, PasswordHash, RoleID, IsActive, CreatedAt, UpdatedAt) VALUES (:fullName, :email, :passwordHash, :roleId, TRUE, NOW(), NOW())");

            // If UserID is UUID and you need to generate it in PHP (example):
            $userId = $this->generateUuid(); // You'd need a UUID generation method

            $stmt = $this->db->prepare(
                "INSERT INTO Users (UserID, FullName, Email, PasswordHash, Salt, RoleID, IsActive, CreatedAt, UpdatedAt, PasswordLastChangedAt)
                 VALUES (:userId, :fullName, :email, :passwordHash, :salt, :roleId, TRUE, NOW(), NOW(), NOW())"
            );

            // Note: The 'Salt' column was added in the conceptual review.
            // password_hash() with ARGON2ID or BCRYPT handles salt generation internally.
            // The 'salt' is part of the generated $passwordHash string itself.
            // So, you don't store a separate salt column if using password_hash() correctly.
            // I'll remove 'salt' from the INSERT for now, assuming modern password_hash usage.
            // If you have a specific reason for a separate salt column with an older hashing method, adjust accordingly.

            $stmt = $this->db->prepare(
                "INSERT INTO Users (UserID, FullName, Email, PasswordHash, RoleID, IsActive, CreatedAt, UpdatedAt, PasswordLastChangedAt)
                 VALUES (:userId, :fullName, :email, :passwordHash, :roleId, TRUE, NOW(), NOW(), NOW())"
            );

            $stmt->bindParam(':userId', $userId); // If generating UserID in PHP
            $stmt->bindParam(':fullName', $fullName);
            $stmt->bindParam(':email', $email);
            $stmt->bindParam(':passwordHash', $passwordHash);
            $stmt->bindParam(':roleId', $roleId, PDO::PARAM_INT);

            $stmt->execute();

            // If UserID is auto-increment: return $this->db->lastInsertId();
            return $userId; // If generating UserID in PHP

        } catch (PDOException $e) {
            error_log("Error creating user: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Helper to generate a UUID (v4).
     * Requires random_bytes if available, or a fallback (less secure).
     * @return string
     */
    private function generateUuid(): string {
        if (function_exists('random_bytes')) {
            $data = random_bytes(16);
            $data[6] = chr(ord($data[6]) & 0x0f | 0x40); // set version to 0100
            $data[8] = chr(ord($data[8]) & 0x3f | 0x80); // set bits 6-7 to 10
            return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
        }
        // Fallback (not cryptographically strong for session IDs, but okay for unique IDs if random_bytes unavailable)
        return sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
            mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff),
            mt_rand(0, 0x0fff) | 0x4000, mt_rand(0, 0x3fff) | 0x8000,
            mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff)
        );
    }
}
?>
